services:
  backend:
    
    image: eelusss-backend:1.0
    
    build:
      context: .
      dockerfile: Dockerfile

    container_name: eelusss-backend

    ports:
      - "4000:4000"

    env_file:
      - .env

    restart: unless-stopped