'use client'

import { Calendar, Clock, Edit, Trash2, Eye, Cpu, User } from 'lucide-react'
import { Badge } from '@/components/ui/Badge'
import { Button } from '@/components/ui/Button'
import { Schedule } from './types'
import { cn } from '@/lib/utils'

interface ScheduleCardProps {
    schedule: Schedule
    onView: (schedule: Schedule) => void
    onEdit: (schedule: Schedule) => void
    onDelete: (schedule: Schedule) => void
}

export function ScheduleCard({ schedule, onView, onEdit, onDelete }: ScheduleCardProps) {
    const formatDate = (dateString: string) => {
        const date = new Date(dateString)
        return date.toLocaleDateString('en-US', {
            year: 'numeric',
            month: 'short',
            day: 'numeric',
        })
    }

    return (
        <div className="bg-gray-800 rounded-xl border border-gray-700 p-5 hover:border-gray-600 transition-all duration-300 group">
            {/* Header */}
            <div className="flex items-start justify-between mb-4">
                <div className="flex-1">
                    <div className="flex items-center gap-3 mb-2">
                        <div className={cn(
                            'w-10 h-10 rounded-lg flex items-center justify-center',
                            schedule.status === 'published'
                                ? 'bg-green-500/20 text-green-400'
                                : 'bg-yellow-500/20 text-yellow-400'
                        )}>
                            <Calendar className="w-5 h-5" />
                        </div>
                        <div>
                            <h3 className="text-white font-semibold text-lg group-hover:text-teal-400 transition-colors">
                                {schedule.name}
                            </h3>
                            <p className="text-gray-400 text-sm">{schedule.collegeName}</p>
                        </div>
                    </div>
                </div>
                <Badge variant={schedule.status === 'published' ? 'published' : 'draft'}>
                    {schedule.status === 'published' ? 'Published' : 'Draft'}
                </Badge>
            </div>

            {/* Info */}
            <div className="space-y-3 mb-4">
                <div className="flex items-center gap-2 text-gray-400 text-sm">
                    <Clock className="w-4 h-4" />
                    <span>Last updated: {formatDate(schedule.updatedAt)}</span>
                </div>
                <div className="flex items-center gap-2 text-gray-400 text-sm">
                    {schedule.generatedBy === 'ai' ? (
                        <>
                            <Cpu className="w-4 h-4 text-purple-400" />
                            <span className="text-purple-400">Generated by AI</span>
                        </>
                    ) : (
                        <>
                            <User className="w-4 h-4 text-blue-400" />
                            <span className="text-blue-400">Created Manually</span>
                        </>
                    )}
                </div>
                <div className="flex items-center gap-2 text-gray-400 text-sm">
                    <span className="bg-gray-700 px-2 py-1 rounded-md text-xs">
                        {schedule.events.length} Lectures
                    </span>
                </div>
            </div>

            {/* Actions */}
            <div className="flex items-center gap-2 pt-4 border-t border-gray-700">
                <Button
                    variant="secondary"
                    icon={<Eye className="w-4 h-4" />}
                    onClick={() => onView(schedule)}
                    className="flex-1 text-sm"
                >
                    View
                </Button>
                <Button
                    variant="primary"
                    icon={<Edit className="w-4 h-4" />}
                    onClick={() => onEdit(schedule)}
                    className="flex-1 text-sm"
                >
                    Edit
                </Button>
                <button
                    onClick={() => onDelete(schedule)}
                    className="p-2 rounded-lg bg-gray-700 hover:bg-red-600/30 text-gray-400 hover:text-red-400 transition-all"
                >
                    <Trash2 className="w-4 h-4" />
                </button>
            </div>
        </div>
    )
}
